### ISSUE TITLE
TeamViewer Install broken

### ISSUE THREAD

**Issue by bigrammy** [getsolus/3rd-party#48]
**Edit:** The TeamViewer website is down so this is probably the issue.
"_www.teamviewer.com sent an invalid response.
ERR_SSL_PROTOCOL_ERROR_"  Hopefully not a permanent issue.

The Teamviewer installation is broken and freezes the software center. 
![teamviewer-install-error](https://user-images.githubusercontent.com/20744097/94341270-d005b600-ffff-11ea-8b9a-b2c228b39217.png)

Budgie "Solus 4.1 Fortitude"  fully updated. 

PS: Please Add Google's remote desktop https://remotedesktop.google.com as a option. It seems to work for other distros. :+1:  
https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb

**Comment by Staudey** [comment]
Hello there: As you wrote in your edit that was just a temporary issue on Teamviewer's side. Should work now (just tried it myself).

> PS: Please Add Google's remote desktop https://remotedesktop.google.com as a option. It seems to work for other distros. +1
https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb

Unfortunately no new software will be added to the Third Party Repository. But does this really require additional tools? Shouldn't that work with the Chrome Browser alone? (Sorry if that is a stupid question, I've never used it).

**Comment by bigrammy** [comment]
> Hello there: As you wrote in your edit that was just a temporary issue on Teamviewer's side. Should work now (just tried it myself).
> 
> > PS: Please Add Google's remote desktop https://remotedesktop.google.com as a option. It seems to work for other distros. +1
> > https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
> 
> Unfortunately no new software will be added to the Third Party Repository. But does this really require additional tools? Shouldn't that work with the Chrome Browser alone? (Sorry if that is a stupid question, I've never used it).

Hmm, Not sure as it's above my pay grade really. I assume for chrome to take full control of the PC it would need more than it does normally. I had a quick look through the .deb it downloaded (link above) but I am unsure where it places everything and what permissions it sets etc.
As for the Teamviewer it's still broken for me and the website still says the same as I quoted above. Very Strange :-1:
I posted on the forum too about chrome https://discuss.getsol.us/d/208-remote-desktop-software/24 

Thanks for the consideration :+1:   Hopefully teamviewer will sort out their website soon :-1:
